### ISSUE TITLE
How to build SLAMBench itself when using docker?

### ISSUE THREAD

**Issue by yrq0208** [nikolaradulov/SLAMFuse#20]
Currently, the Wiki covers how to build datasets when using docker ([https://github.com/nikolaradulov/slambench/wiki/Demos](url)) and how to build algorithms when using docker ([https://github.com/nikolaradulov/slambench/wiki/Volume-for-Algorithm](url)), but the part of building SLAMBench itself ([https://github.com/nikolaradulov/slambench/wiki/Container-SLAMBench-for-WSL](url)) seems to be missing.

I have managed to build ORB-SLAM3 with the SLAMBench-container branch, but when I tried to list the datasets using "python3 starter.py dataset -t list" I got "Unable to find image 'slambench/main:latest' locally docker: Error response from daemon: pull access denied for slambench/main, repository does not exist or may require 'docker login': denied: requested access to the resource is denied." I guess this is because I haven't built SLAMBench itself. 

Also when trying to build kfusion, LSD-SLAM and ORB-SLAM2 I run into the same error, see attached screenshots.
![orbslam2_container_error](https://github.com/nikolaradulov/slambench/assets/34848593/bc4a5984-2718-406d-b092-7e1736308f66)
![lsdslam_container_error](https://github.com/nikolaradulov/slambench/assets/34848593/bfda1c2d-5a3e-4734-8812-a57394ab9563)
![kfusion_container_error](https://github.com/nikolaradulov/slambench/assets/34848593/55aac329-69e8-48f5-9926-a640f6ca58a9)

**Comment by yuhaozhang7** [comment]
Hi @yrq0208 
For "Also when trying to build kfusion, LSD-SLAM and ORB-SLAM2 I run into the same error, see attached screenshots.", it is because the latest changes in branch `algorithm_volume` is not merged into `SLAMBench-conteinarisation`

I just update the full instructions, start with git clone, for generating algorithm volume, and run the algorithm on slambench.
https://github.com/nikolaradulov/slambench/wiki/Volume-for-Algorithm

**Comment by nikolaradulov** [comment]
@yrq0208  This is my own idiocy. The plan is to have the slambench container in it's final form downloadable using docker, so you wouldn't even need to go through the process of building it. but that's stupid since people will seek to build it regardless. That being said **to build it**:

- from the ./slambench directory simply run  `docker build . -t slambench/main'  then using the starter should work. If it doesn't , please let me know and i'll look into it.
